//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomMoskovskikh2023.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Диплом_Катя1 : DbContext
    {
        public Диплом_Катя1()
            : base("name=Диплом_Катя1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Soderzhanie> Soderzhanie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Виды_Контроля> Виды_Контроля { get; set; }
        public virtual DbSet<Вопросы> Вопросы { get; set; }
        public virtual DbSet<Даты> Даты { get; set; }
        public virtual DbSet<Дневник_Учителя> Дневник_Учителя { get; set; }
        public virtual DbSet<Модули> Модули { get; set; }
        public virtual DbSet<Ответы> Ответы { get; set; }
        public virtual DbSet<Правильные_неправильные_ответы> Правильные_неправильные_ответы { get; set; }
        public virtual DbSet<РезультатыТеста> РезультатыТеста { get; set; }
        public virtual DbSet<Термины> Термины { get; set; }
    }
}
