//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomMoskovskikh2023.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вопросы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Вопросы()
        {
            this.Ответы = new HashSet<Ответы>();
        }
    
        public int ID_вопроса { get; set; }
        public int id_теста { get; set; }
        public string Вопрос { get; set; }
        public Nullable<int> Id_модуля { get; set; }
    
        public virtual Виды_Контроля Виды_Контроля { get; set; }
        public virtual Модули Модули { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ответы> Ответы { get; set; }
    }
}
