//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomMoskovskikh2023.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Даты
    {
        public int id { get; set; }
        public string Описание { get; set; }
        public Nullable<int> id_модули { get; set; }
    
        public virtual Модули Модули { get; set; }
    }
}
