//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomMoskovskikh2023.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ответы
    {
        public int Id_Ответа { get; set; }
        public int id_вопроса { get; set; }
        public string Ответ { get; set; }
        public Nullable<int> id_верных_ответов { get; set; }
        public Nullable<int> id_модуля { get; set; }
    
        public virtual Вопросы Вопросы { get; set; }
        public virtual Модули Модули { get; set; }
        public virtual Правильные_неправильные_ответы Правильные_неправильные_ответы { get; set; }
    }
}
