//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomMoskovskikh2023.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class РезультатыТеста
    {
        public int ID_тестирования { get; set; }
        public int Id_Ученика { get; set; }
        public int id_темы { get; set; }
        public Nullable<int> КоличествоНеверных { get; set; }
        public Nullable<int> КоличествоВсехВопросов { get; set; }
        public System.DateTime Дата { get; set; }
    
        public virtual User User { get; set; }
        public virtual Виды_Контроля Виды_Контроля { get; set; }
    }
}
